### ISSUE TITLE
Investigate End of Game Crash

### ISSUE THREAD

**Issue by Hedgemon4** [Hedgemon4/COSC322-Project#14]
Investigate the end of the game crashing which is occurring.

**Comment by Hedgemon4** [comment]
Error Message:
1834564 [New I/O client worker #1-1] ERROR sfs2x.client.core.EventDispatcher - Error dispatching event extensionResponse :Cannot invoke "Tree.Node.isLeaf()" because "current" is null
java.lang.NullPointerException: Cannot invoke "Tree.Node.isLeaf()" because "current" is null
	at Tree.MonteCarloTree.select(MonteCarloTree.java:29)
	at Tree.MonteCarloTree.search(MonteCarloTree.java:18)
	at Main.makeMonteCarloMove(Main.java:126)
	at Main.makeMove(Main.java:119)
	at Main.handleGameMessage(Main.java:110)
	at ygraph.ai.smartfox.games.GameClient$EventHandler.dispatchGameMessage(GameClient.java:399)
	at ygraph.ai.smartfox.games.GameClient$EventHandler.dispatch(GameClient.java:465)
	at sfs2x.client.core.EventDispatcher.dispatchEvent(EventDispatcher.java:60)
	at sfs2x.client.SmartFox.dispatchEvent(SmartFox.java:1478)
	at sfs2x.client.controllers.ExtensionController.handleMessage(ExtensionController.java:55)
	at sfs2x.client.core.SFSProtocolCodec.dispatchRequest(SFSProtocolCodec.java:152)
	at sfs2x.client.core.SFSProtocolCodec.onPacketRead(SFSProtocolCodec.java:57)
	at sfs2x.client.core.SFSIOHandler.handlePacketData(SFSIOHandler.java:316)
	at sfs2x.client.core.SFSIOHandler.onDataRead(SFSIOHandler.java:138)
	at sfs2x.client.bitswarm.BitSwarmClient.onSocketData(BitSwarmClient.java:405)
	at sfs2x.client.bitswarm.BitSwarmClient.access$2(BitSwarmClient.java:399)
	at sfs2x.client.bitswarm.BitSwarmClient$3.dispatch(BitSwarmClient.java:116)
	at sfs2x.client.core.EventDispatcher.dispatchEvent(EventDispatcher.java:60)
	at sfs2x.client.core.sockets.TCPSocketLayer.callOnData(TCPSocketLayer.java:195)
	at sfs2x.client.core.sockets.TCPSocketLayer.handleBinaryData(TCPSocketLayer.java:188)
	at sfs2x.client.core.sockets.TCPSocketLayer.access$7(TCPSocketLayer.java:186)
	at sfs2x.client.core.sockets.TCPSocketLayer$NettyIOHandler.messageReceived(TCPSocketLayer.java:355)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:545)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:540)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Hedgemon4** [comment]
Closed with the above branch
